=== playlogo/NOCR/jobs/utils/job.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "requires": {
            "type": "array",
            "description": "Modules used by job",
            "items": {
                "type": "string"
            }
        },
        "schedules": {
            "type": "array",
            "description": "Cron schedule expressions",
            "items": {
                "type": "string"
            }
        },
        "executable": {
            "type": "string",
            "description": "Path to executable"
        },
        "args": {
            "type": "array",
            "description": "Start arguments for executable",
            "items": {
                "type": "string"
            }
        },
        "env": {
            "type": "array",
            "description": "Pass down env variables",
            "items": {
                "type": "string"
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "requires",
        "schedules",
        "executable",
        "args"
    ]
}

=== playlogo/NOCR/jobs/3djake/job.json
{
    "$schema": "../utils/job.schema.json",
    "schedules": [
        "0 6 * * *",
        "0 14 * * *",
        "0 20 * * *"
    ],
    "executable": "~/.deno/bin/deno",
    "args": [
        "run",
        "--allow-all",
        "main.ts"
    ],
    "requires": [
        "mongo",
        "ntfy"
    ],
    "env": [
        "GROQ_API_KEY"
    ]
}
